import { BookOpen, Boxes, Code2, Database, FileQuestion, Landmark, LockKeyhole, Plug, Rocket, Server, Shield, Sparkles } from "lucide-react";

export type ListItem = {
  title: string;
  href?: string;
  group?: boolean;
  separator?: boolean;
  external?: boolean;
  subpages?: ListItem[];
};

export const contents = [
  {
    title: "Start",
    Icon: Rocket,
    list: [
      { title: "Introduction", href: "/docs/introduction" },
      { title: "Installation", href: "/docs/installation" },
      { title: "Basic Usage", href: "/docs/basic-usage" },
      { title: "Comparison", href: "/docs/comparison" },
    ],
  },
  {
    title: "Concepts",
    Icon: BookOpen,
    expandSectionForPathPrefix: "/docs/concepts",
    list: [
      { title: "API", href: "/docs/concepts/api" },
      { title: "CLI", href: "/docs/concepts/cli" },
      { title: "Client", href: "/docs/concepts/client" },
      { title: "Cookies", href: "/docs/concepts/cookies" },
      { title: "Database", href: "/docs/concepts/database" },
      { title: "Email", href: "/docs/concepts/email" },
      { title: "Hooks", href: "/docs/concepts/hooks" },
      { title: "OAuth", href: "/docs/concepts/oauth" },
      { title: "Plugins", href: "/docs/concepts/plugins" },
      { title: "Rate Limit", href: "/docs/concepts/rate-limit" },
      { title: "Sessions", href: "/docs/concepts/session-management" },
      { title: "Users and Accounts", href: "/docs/concepts/users-accounts" },
      { title: "Admin Config", href: "/docs/concepts/admin-config" },
      { title: "Billing", href: "/docs/concepts/billing" },
      { title: "Security", href: "/docs/concepts/security" },
    ],
  },
  {
    title: "Authentication",
    Icon: LockKeyhole,
    expandSectionForPathPrefix: "/docs/authentication",
    list: [
      { title: "Email Password", href: "/docs/authentication/email-password" },
      { title: "GitHub", href: "/docs/authentication/github" },
      { title: "Google", href: "/docs/authentication/google" },
      { title: "Microsoft", href: "/docs/authentication/microsoft" },
      { title: "Apple", href: "/docs/authentication/apple" },
      { title: "Discord", href: "/docs/authentication/discord" },
      { title: "Facebook", href: "/docs/authentication/facebook" },
      { title: "GitLab", href: "/docs/authentication/gitlab" },
      { title: "LinkedIn", href: "/docs/authentication/linkedin" },
      { title: "Slack", href: "/docs/authentication/slack" },
      { title: "Spotify", href: "/docs/authentication/spotify" },
      { title: "Twitter", href: "/docs/authentication/twitter" },
      { title: "Other Providers", href: "/docs/authentication/other-social-providers" },
    ],
  },
  {
    title: "Adapters",
    Icon: Database,
    expandSectionForPathPrefix: "/docs/adapters",
    list: [
      { title: "SQLAlchemy", href: "/docs/adapters/sqlalchemy" },
      { title: "SQLite", href: "/docs/adapters/sqlite" },
      { title: "PostgreSQL", href: "/docs/adapters/postgresql" },
      { title: "MySQL", href: "/docs/adapters/mysql" },
      { title: "MSSQL", href: "/docs/adapters/mssql" },
      { title: "Mongo", href: "/docs/adapters/mongo" },
      { title: "Redis Storage", href: "/docs/adapters/redis-storage" },
      { title: "Memory", href: "/docs/adapters/memory" },
      { title: "Community", href: "/docs/adapters/community-adapters" },
    ],
  },
  {
    title: "Plugins",
    Icon: Plug,
    expandSectionForPathPrefix: "/docs/plugins",
    list: [
      { title: "Overview", href: "/docs/plugins" },
      { title: "Two Factor", href: "/docs/plugins/2fa" },
      { title: "Admin", href: "/docs/plugins/admin" },
      { title: "Admin Config", href: "/docs/plugins/admin-config" },
      { title: "Anonymous", href: "/docs/plugins/anonymous" },
      { title: "API Key", href: "/docs/plugins/api-key" },
      { title: "Bearer", href: "/docs/plugins/bearer" },
      { title: "Captcha", href: "/docs/plugins/captcha" },
      { title: "Device Authorization", href: "/docs/plugins/device-authorization" },
      { title: "Email OTP", href: "/docs/plugins/email-otp" },
      { title: "Generic OAuth", href: "/docs/plugins/generic-oauth" },
      { title: "Have I Been Pwned", href: "/docs/plugins/have-i-been-pwned" },
      { title: "JWT", href: "/docs/plugins/jwt" },
      { title: "Last Login Method", href: "/docs/plugins/last-login-method" },
      { title: "Magic Link", href: "/docs/plugins/magic-link" },
      { title: "MCP", href: "/docs/plugins/mcp" },
      { title: "Multi Session", href: "/docs/plugins/multi-session" },
      { title: "OAuth Provider", href: "/docs/plugins/oauth-provider" },
      { title: "OAuth Proxy", href: "/docs/plugins/oauth-proxy" },
      { title: "OIDC Provider", href: "/docs/plugins/oidc-provider" },
      { title: "One Tap", href: "/docs/plugins/one-tap" },
      { title: "One Time Token", href: "/docs/plugins/one-time-token" },
      { title: "Open API", href: "/docs/plugins/open-api" },
      { title: "Organization", href: "/docs/plugins/organization" },
      { title: "Passkey", href: "/docs/plugins/passkey" },
      { title: "Phone Number", href: "/docs/plugins/phone-number" },
      { title: "SCIM", href: "/docs/plugins/scim" },
      { title: "SIWE", href: "/docs/plugins/siwe" },
      { title: "SSO", href: "/docs/plugins/sso" },
      { title: "Stripe", href: "/docs/plugins/stripe" },
      { title: "Test Utils", href: "/docs/plugins/test-utils" },
      { title: "Username", href: "/docs/plugins/username" },
    ],
  },
  {
    title: "Integrations",
    Icon: Server,
    expandSectionForPathPrefix: "/docs/integrations",
    list: [
      { title: "FastAPI", href: "/docs/integrations/fastapi" },
      { title: "Starlette", href: "/docs/integrations/starlette" },
      { title: "Django", href: "/docs/integrations/django" },
      { title: "Next.js", href: "/docs/integrations/next" },
      { title: "Nuxt", href: "/docs/integrations/nuxt" },
      { title: "SvelteKit", href: "/docs/integrations/svelte-kit" },
      { title: "React Router", href: "/docs/integrations/react-router" },
      { title: "Astro", href: "/docs/integrations/astro" },
      { title: "Expo", href: "/docs/integrations/expo" },
      { title: "Electron", href: "/docs/integrations/electron" },
    ],
  },
  {
    title: "Guides",
    Icon: Sparkles,
    expandSectionForPathPrefix: "/docs/guides",
    list: [
      { title: "Your First Plugin", href: "/docs/guides/your-first-plugin" },
      { title: "Create Adapter", href: "/docs/guides/create-a-db-adapter" },
      { title: "Dynamic Base URL", href: "/docs/guides/dynamic-base-url" },
      { title: "Performance", href: "/docs/guides/optimizing-for-performance" },
      { title: "Browser Extension", href: "/docs/guides/browser-extension-guide" },
      { title: "Auth0 Migration", href: "/docs/guides/auth0-migration-guide" },
      { title: "Clerk Migration", href: "/docs/guides/clerk-migration-guide" },
      { title: "NextAuth Migration", href: "/docs/guides/next-auth-migration-guide" },
      { title: "Supabase Migration", href: "/docs/guides/supabase-migration-guide" },
      { title: "WorkOS Migration", href: "/docs/guides/workos-migration-guide" },
    ],
  },
  {
    title: "Examples",
    Icon: Code2,
    expandSectionForPathPrefix: "/docs/examples",
    list: [
      { title: "FastAPI SaaS Demo", href: "/docs/examples/fastapi-saas-demo" },
      { title: "Vite Client", href: "/docs/examples/vite-client" },
      { title: "Next.js", href: "/docs/examples/next-js" },
      { title: "React Router", href: "/docs/examples/react-router" },
      { title: "SvelteKit", href: "/docs/examples/svelte-kit" },
      { title: "Deployment", href: "/docs/examples/deployment" },
    ],
  },
  {
    title: "Infrastructure",
    Icon: Landmark,
    expandSectionForPathPrefix: "/docs/infrastructure",
    list: [
      { title: "Introduction", href: "/docs/infrastructure/introduction" },
      { title: "Getting Started", href: "/docs/infrastructure/getting-started" },
      { title: "Email Service", href: "/docs/infrastructure/services/email" },
      { title: "SMS Service", href: "/docs/infrastructure/services/sms" },
      { title: "Audit Logs", href: "/docs/infrastructure/plugins/audit-logs" },
      { title: "Dashboard", href: "/docs/infrastructure/plugins/dashboard" },
      { title: "Sentinel", href: "/docs/infrastructure/plugins/sentinel" },
    ],
  },
  {
    title: "Reference",
    Icon: FileQuestion,
    expandSectionForPathPrefix: "/docs/reference",
    list: [
      { title: "CLI", href: "/docs/reference/cli" },
      { title: "Options", href: "/docs/reference/options" },
      { title: "Routes", href: "/docs/reference/routes" },
      { title: "Errors", href: "/docs/reference/errors" },
      { title: "Security", href: "/docs/reference/security" },
      { title: "Testing", href: "/docs/reference/testing" },
      { title: "FAQ", href: "/docs/reference/faq" },
      { title: "Contributing", href: "/docs/reference/contributing" },
    ],
  },
];
