"""`better-auth init` — scaffold a minimal app starter.

Mirrors `reference/packages/cli/src/commands/init/index.ts` but stripped to the
essentials a Python app needs: an `auth.py` file with a working `init(...)` call,
and a `.env.example` with a generated secret + DB url placeholder.
"""

from __future__ import annotations

from pathlib import Path

import click

from better_auth_cli.commands.secret import generate_secret


ADAPTER_IMPORTS: dict[str, tuple[str, str]] = {
    "memory": (
        "from better_auth_memory_adapter import memory_adapter",
        "memory_adapter()",
    ),
    "sqlite": (
        "from better_auth_sqlalchemy import sqlalchemy_adapter\n"
        "from sqlalchemy.ext.asyncio import create_async_engine",
        'sqlalchemy_adapter(create_async_engine(os.environ["DATABASE_URL"]))',
    ),
    "postgres": (
        "from better_auth_sqlalchemy import sqlalchemy_adapter\n"
        "from sqlalchemy.ext.asyncio import create_async_engine",
        'sqlalchemy_adapter(create_async_engine(os.environ["DATABASE_URL"]))',
    ),
    "mysql": (
        "from better_auth_sqlalchemy import sqlalchemy_adapter\n"
        "from sqlalchemy.ext.asyncio import create_async_engine",
        'sqlalchemy_adapter(create_async_engine(os.environ["DATABASE_URL"]))',
    ),
    "mongo": (
        "from better_auth_mongo import mongo_adapter\n"
        "from motor.motor_asyncio import AsyncIOMotorClient",
        'mongo_adapter(AsyncIOMotorClient(os.environ["MONGO_URL"]).get_default_database())',
    ),
}

ADAPTER_DB_URL: dict[str, str] = {
    "memory": "DATABASE_URL=memory://",
    "sqlite": "DATABASE_URL=sqlite+aiosqlite:///./app.db",
    "postgres": "DATABASE_URL=postgresql+asyncpg://user:pass@localhost:5432/app",
    "mysql": "DATABASE_URL=mysql+aiomysql://user:pass@localhost:3306/app",
    "mongo": "MONGO_URL=mongodb://localhost:27017/app",
}

FRAMEWORK_SNIPPETS: dict[str, str] = {
    "fastapi": """\

# --- FastAPI mount ---
# from fastapi import FastAPI
# from better_auth_fastapi import mount_auth
#
# app = FastAPI()
# mount_auth(app, auth)
""",
    "starlette": """\

# --- Starlette mount ---
# from starlette.applications import Starlette
# from better_auth_starlette import mount_auth
#
# app = Starlette()
# mount_auth(app, auth)
""",
    "django": """\

# --- Django mount ---
# In your urls.py:
# from better_auth_django import auth_urlpatterns
# urlpatterns = [..., *auth_urlpatterns(auth)]
""",
    "none": "",
}


def _auth_py(adapter: str, framework: str) -> str:
    import_line, adapter_call = ADAPTER_IMPORTS[adapter]
    return f'''"""better-auth setup."""

from __future__ import annotations

import os

from better_auth import BetterAuthOptions
from better_auth.auth import init
from better_auth.plugins.email_password import email_and_password
{import_line}


auth = init(
    BetterAuthOptions(
        database={adapter_call},
        secret=os.environ.get("BETTER_AUTH_SECRET", "change-me"),
        base_url=os.environ.get("BETTER_AUTH_URL", "http://localhost:3000"),
        plugins=[email_and_password()],
    )
)
{FRAMEWORK_SNIPPETS[framework]}'''


def _env_example(adapter: str) -> str:
    return f"""# Generated by `better-auth init`
BETTER_AUTH_SECRET={generate_secret()}
BETTER_AUTH_URL=http://localhost:3000
{ADAPTER_DB_URL[adapter]}
"""


@click.command("init", help="Scaffold a minimal better-auth project.")
@click.option(
    "--cwd",
    type=click.Path(file_okay=False, dir_okay=True, resolve_path=True),
    default=".",
    show_default=True,
    help="Target directory (defaults to current).",
)
@click.option(
    "--adapter",
    type=click.Choice(list(ADAPTER_IMPORTS.keys())),
    default="memory",
    show_default=True,
    help="Database adapter to scaffold.",
)
@click.option(
    "--framework",
    type=click.Choice(list(FRAMEWORK_SNIPPETS.keys())),
    default="none",
    show_default=True,
    help="Optional framework mount snippet.",
)
@click.option(
    "--force",
    is_flag=True,
    default=False,
    help="Overwrite existing files.",
)
def init(cwd: str, adapter: str, framework: str, force: bool) -> None:
    root = Path(cwd)
    root.mkdir(parents=True, exist_ok=True)

    auth_path = root / "auth.py"
    env_path = root / ".env.example"

    if auth_path.exists() and not force:
        raise click.ClickException(
            f"auth.py already exists at {auth_path}. Pass --force to overwrite."
        )

    auth_path.write_text(_auth_py(adapter, framework))
    env_path.write_text(_env_example(adapter))

    click.echo(f"  wrote {auth_path}")
    click.echo(f"  wrote {env_path}")
    click.echo("")
    click.echo("Next steps:")
    click.echo("  1. cp .env.example .env  (then edit)")
    click.echo("  2. better-auth generate  (write the schema migration)")
    click.echo("  3. better-auth migrate   (apply it)")
